### ISSUE TITLE
"Make you build" tab

### ISSUE THREAD

**Issue by Zweer** [dfilipidisz/overwolf-hots-talents#4]
Hey,

first of all great job for the app!!

I was using your app and discovered I don't have the possibility to put my own build in the overlay, but only see others' builds...
What about implementing a tab where you can put your own build, even only with numbers (1st talent at lvl 1, 3rd at lvl 4...)

If that sounds good for you I can help you since I know a bit of js and html...

Let me know...
Cya

**Comment by dfilipidisz** [comment]
Hey Zweer,

The idea sounds good, if you have the time/will to do it I would appreciate a PR on this one! :)
